workflows:
  build-android:
    name: Build Android APK
    working_directory: realcom1-main
    environment:
      flutter: 3.24.0
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
